### ISSUE TITLE
This "complete" value will always be "false" for get /v2/kafka/(cluster)/consumer/(group)/status

### ISSUE THREAD

**Issue by DavidLiuXh** [linkedin/Burrow#35] opened 2015-11-13 06:39 UTC
If a consumer group has been a long did not commit offset when startup a Burrow, since "if offset.Timestamp-previousTimestamp < (storage.app.Config.Lagcheck.MinDistance * 1000)",
this "complete" value will always be "false" for get /v2/kafka/(cluster)/consumer/(group)/status

**Comment by DavidLiuXh** [comment] 2015-11-13 06:39
if offset.Timestamp-previousTimestamp < (storage.app.Config.Lagcheck.MinDistance*1000)

=>

if storage.offsets[offset.Cluster].consumer[offset.Group][offset.Topic][offset.Partition].Value != nil && offset.Timestamp-previousTimestamp < (storage.app.Config.Lagcheck.MinDistance*1000)

Is this ok？

**Comment by toddpalino** [comment] 2015-11-13 20:36
If a consumer is not committing offsets, then it is appropriate that complete will return as false. The consumer must be active for Burrow to monitor it. There is no effective status check for a consumer group that has not been running since Burrow was started.

The change you have proposed has a similar effect to the last one, which is that the MinDistance check is skipped and will cause the same Zookeeper-committed offset to be written to the ring over and over to initially fill it. This is not correct behavior, as each value in the offset ring is supposed to represent a single offset commit.

**Comment by DavidLiuXh** [comment] 2015-11-16 01:43
1.  If a consumer is normally, but no  data submitted to the kafka broker, this consumer also does not submitted offsets, What is the behavior of the Burrow?

2. If use the same group name of consumer to spend a different A and B topics. 	Assume no  data submitted to the A topic,  but the data has been submitted to B topic, this "complete" value will always be "false" for get /v2/kafka/(cluster)/consumer/(group)/status.

**Comment by toddpalino** [comment] 2015-12-01 22:32
For Kafka-committed offsets, the auto offset commit works appropriately. That is, it will commit the offset regardless of whether or not it has changed. The problem is that for ZK-committed offsets, the auto offset commit will short-circuit the write if the value has not changed. This presents a problem for us in this type of situation.

I have no good answer for this. Your proposals would result in the offset ring getting filled up with the same value. Consider the case where at one point there was a ZK consumer group on a topic, and it has gone away. If we implemented your proposals, this group would continually be considered to be in a bad state (the consumer offset is not changing, but the lag is increasing).

**Comment by toddpalino** [comment] 2015-12-21 19:41
I just added a patch for #38 to support ZK consumers on slow topics. This should resolve the slow/no data case. Unfortunately, there's not much that can be done about the completeness of a ZK consumer who consumes a topic that never gets any data. If it has any data at all, the consumer will eventually be marked complete.

**Comment by DavidLiuXh** [comment] 2015-12-22 02:36
Thanks for @toddpalino, I will use it.

**Closed** 2016-03-07 23:20 UTC
