### ISSUE TITLE
[1.0.0] concurrent map read and map write panic

### ISSUE THREAD

**Issue by xushichangdesmond** [linkedin/Burrow#315] opened 2017-12-27 04:16 UTC
My burrow instance that is monitoring a large cluster with many topics and consumers died due to a panic for concurrent map read and write.

`
Reading configuration from /opt/burrow/instance/config
fatal error: concurrent map read and map write
fatal error: concurrent map read and map write

goroutine 500215147 [running]:
runtime.throw(0x9dd3f0, 0x21)
        /usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:605 +0x95 fp=0xc42be32b98 sp=0xc42be32b78 pc=0x42b795
runtime.mapaccess1_faststr(0x923f00, 0xc42bb16600, 0xc42d7b7a60, 0x20, 0xc425e919b8)
        /usr/local/Cellar/go/1.9.2/libexec/src/runtime/hashmap_fast.go:217 +0x43a fp=0xc42be32bf0 sp=0xc42be32b98 pc=0x40bb2a
github.com/linkedin/Burrow/core/internal/consumer.(*KafkaZkClient).resetPartitionListWatchAndAdd(0xc4200ba790, 0xc42ac9a600, 0x1a, 0xc42d7b7a60, 0x20, 0xc42ac9a600)
        /Users/dxu/work/2017.4.10/src/github.com/linkedin/Burrow/core/internal/consumer/kafka_zk_client.go:317 +0x5c0 fp=0xc42be32fb0 sp=0xc42be32bf0 pc=0x851420
runtime.goexit()
        /usr/local/Cellar/go/1.9.2/libexec/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc42be32fb8 sp=0xc42be32fb0 pc=0x459d91
created by github.com/linkedin/Burrow/core/internal/consumer.(*KafkaZkClient).watchPartitionList
        /Users/dxu/work/2017.4.10/src/github.com/linkedin/Burrow/core/internal/consumer/kafka_zk_client.go:295 +0x17d
`

**Comment by toddpalino** [comment] 2018-01-13 16:12
It looks like the problem is specifically the code section in kafka_zk_client.go from 316-331. The code needs to dive down into the groups map, but it does not first get a read lock on groupLock. It also needs to get read on the topicList.lock. Only then can it get the lock on partitionList.lock.

This will require a little bit of restructuring the code there. But it shouldn't require the creation of any new tests.

**Comment by toddpalino** [comment] 2018-01-19 00:56
Closed by #328

**Closed by toddpalino** 2018-01-19 00:56 UTC
Labels: bug
