### ISSUE TITLE
Compilation errors on Windows 7 Professional with go1.5.2.windows-386

### ISSUE THREAD

**Issue by yhilem** [linkedin/Burrow#42] opened 2016-01-06 19:00 UTC
D:\Platform\Go\test-01-Burrow\Burrow>set GOPATH=D:\Platform\Go\test-01-Burrow\Burrow

D:\Platform\Go\test-01-Burrow\Burrow>set GOBIN=D:\Platform\Go\test-01-Burrow\Burrow\bin

D:\Platform\Go\test-01-Burrow\Burrow>go install
# _/D_/Platform/Go/test-01-Burrow/Burrow
.\logger.go:54: undefined: syscall.Dup2
.\logger.go:55: undefined: syscall.Dup2
.\main.go:211: undefined: syscall.SIGSTOP

D:\Platform\Go\test-01-Burrow\Burrow>

**Comment by toddpalino** [comment] 2016-01-12 20:19
Windows is not a target platform for me. The problem is obviously the way that Burrow is setting up the logs and registering signal handlers, but this is not something that I'm going to be able to fix (as I do not have windows systems to work on), nor something that I would work on.

If you have a patch that will resolve the issue, I encourage you to submit a PR for it. Otherwise, I am closing this issue as a "wont fix" as Windows is not a supported platform.

**Closed by toddpalino** 2016-01-12 20:19 UTC
Labels: wontfix
