### ISSUE TITLE
no cluster/group/topic in Kafka cluster status

### ISSUE THREAD

**Issue by imneo1** [linkedin/Burrow#89] opened 2016-07-10 13:49 UTC
Hello,

After starting burrow none of the Kafka Cluster consumers/groups is discovered.

Configuration:

[general]
logdir=/var/log
logconfig=config/logging.cfg
pidfile=burrow.pid
client-id=burrow-lagchecker
group-blacklist=^(console-consumer-|python-kafka-consumer-).*$

[zookeeper]
hostname=i-va-kafka21.our-domain.com
hostname=i-va-kafka22.our-domain.com
hostname=i-va-kafka23.our-domain.com
hostname=i-va-kafka24.our-domain.com
hostname=i-va-kafka25.our-domain.com
port=2181
timeout=6
lock-path=/burrow/notifier

[kafka "NJ"]
broker=xetl1.our-domain.com
broker=xetl2.our-domain.com
broker=xetl3.our-domain.com
broker=xetl4.our-domain.com
broker=xetl5.our-domain.com
broker-port=9092
zookeeper=xetl1.our-domain.com
zookeeper=xetl2.our-domain.com
zookeeper=xetl3.our-domain.com
zookeeper=xetl4.our-domain.com
zookeeper=xetl5.our-domain.com
zookeeper-port=2181
zookeeper-path=/consumers/group1

The Znode info:

[zk: localhost:2181(CONNECTED) 4] ls /consumers/group1
[offsets, owners, ids]

This call:
http://burrow.our-domain/com/v2/kafka

returns no cluster/group/topic

{
error: true,
message: "consumer group not found",
result: null,
request: {
url: "/v2/kafka/NJ/consumer/group1/status",
host: "burrow.our-domain.com",
cluster: "",
group: "",
topic: ""
}
}

This call:

http://burrow.our-domain.com/v2/kafka/NJ/

{
error: false,
message: "cluster detail returned",
cluster: {
zookeepers: [
"[xetl1.our-domain.com]:2181",
"[xetl2.our-domain.com]:2181",
"[xetl3.our-domain.com]:2181",
"[xetl4.our-domain.com]:2181",
"[xetl5.our-domain.com]:2181"
],
zookeeper_port: 2181,
zookeeper_path: "/consumers/group1",
brokers: [
"[xetl1.our-domain.com]:9092",
"[xetl2.our-domain.com]:9092",
"[xetl3.our-domain.com]:9092",
"[xetl4.our-domain.com]:9092",
"[xetl5.our-domain.com]:9092"
],
broker_port: 9092,
offsets_topic: "__consumer_offsets"
},
request: {
url: "/v2/kafka/NJ/",
host: "burrow.our-domain.com",
cluster: "NJ",
group: "",
topic: ""
}
}

from burrow.log

2016-07-10 13:59:03 [INFO] Starting Zookeeper client
2016-07-10 13:59:03 [INFO] Starting Offsets Storage module
2016-07-10 13:59:03 [INFO] Starting HTTP server
2016-07-10 13:59:03 [INFO] Starting Zookeeper client for cluster NJ
2016-07-10 13:59:03 [INFO] Starting Kafka client for cluster NJ
2016-07-10 13:59:03 [INFO] Starting consumers for 50 partitions of __consumer_offsets in cluster NJ
2016-07-10 13:59:17 [INFO] Starting Zookeeper client for cluster VA
2016-07-10 13:59:17 [INFO] Starting Kafka client for cluster VA
2016-07-10 13:59:17 [INFO] Starting consumers for 50 partitions of __consumer_offsets in cluster VA
2016-07-10 13:59:37 [INFO] Acquired Zookeeper notifier lock

I also tried to set only "/consumers" at the zookeeper-path (without the group)

What am i missing here ?

**Comment by toddpalino** [comment] 2016-07-10 19:42
The problem is that you have not enabled Zookeeper offset checking for your Kafka cluster. You need to add the config `zookeeper-offsets=true` to the `[kafka "NJ"]` section of your config.

**Comment by imneo1** [comment] 2016-07-10 19:56
Already tried it before and again now.
still same satus

**Comment by toddpalino** [comment] 2016-07-10 19:58
There's also a bug with non-chroot Zookeeper paths, as well, as noted in #80. Let me take a look at that right now, and see if I can get a patch committed to master for it.

**Comment by imneo1** [comment] 2016-07-10 20:01
Thank you for you quick help with this

**Comment by toddpalino** [comment] 2016-07-10 20:05
OK, #80 was a red herring. There's nothing wrong there that I can tell. However, looking at your config again it appears to be a combination of not specifying `zookeeper-enable` and that your `zookeeper-path` config is not correct. That should point to the root of your Kafka cluster, not anything to do with consumers or a specific consumer. Judging from what you have in your config right now, it should be `zookeeper-path=/`

**Comment by imneo1** [comment] 2016-07-10 20:15
zookeeper-enable is not a valid variable. 
i set zookeeper-path=/     as fist step but when it did not work i tried /consumers 

anyway just tried it again
with:

zookeeper-path=/
zookeeper-offsets=true

still same issue

**Comment by toddpalino** [comment] 2016-07-10 20:25
Sorry, I keep mistyping that config. `zookeeper-offsets` is the right one.

What does the call `/v2/kafka/NJ/consumer` return?

In addition, there is a significant amount of debug level logging in the Zookeeper offset checker. You can set your logging level to DEBUG and there will be a lot more information to work with here.

**Comment by imneo1** [comment] 2016-07-10 20:47
Done.

I see many of those:

2016-07-10 20:46:55 [DEBUG] Dropped offset (noadvance): cluster=NJ topic=servingStatusEvent1 partition=60 group=galtest_004 timestamp=1467899190927 offset=1252 tsdiff=0 lag=259
2016-07-10 20:46:55 [DEBUG] Dropped offset (noadvance): cluster=NJ topic=servingStatusEvent1 partition=63 group=galtest_004 timestamp=1467899190919 offset=1245 tsdiff=0 lag=262
2016-07-10 20:46:55 [DEBUG] Dropped offset (noadvance): cluster=NJ topic=servingStatusEvent1 partition=88 group=galtest_004 timestamp=1467899190934 offset=1252 tsdiff=0 lag=263
2016-07-10 20:46:55 [DEBUG] Dropped offset (noadvance): cluster=NJ topic=servingStatusEvent1 partition=49 group=galtest_004 timestamp=1467899190917 offset=1254 tsdiff=0 lag=263
2016-07-10 20:46:55 [DEBUG] Dropped offset (noadvance): cluster=NJ topic=servingStatusEvent1 partition=76 group=galtest_004 timestamp=1467899190920 offset=1234 tsdiff=0 lag=263
2016-07-10 20:46:55 [DEBUG] Dropped offset (noadvance): cluster=NJ topic=servingStatusEvent1 partition=53 group=galtest_004 timestamp=1467899190933 offset=1250 tsdiff=0 lag=261
2016-07-10 20:46:55 [DEBUG] Dropped offset (noadvance): cluster=NJ topic=servingStatusEvent1 partition=52 group=galtest_004 timestamp=1467899190932 offset=1244 tsdiff=0 lag=263
2016-07-10 20:46:55 [DEBUG] Dropped offset (noadvance): cluster=NJ topic=servingStatusEvent1 partition=46 group=galtest_004 timestamp=1467899190919 offset=1234 tsdiff=0 lag=262
2016-07-10 20:46:55 [DEBUG] Dropped offset (noadvance): cluster=NJ topic=servingStatusEvent1 partition=54 group=galtest_004 timestamp=1467899190925 offset=1248 tsdiff=0 lag=262
2016-07-10 20:46:55 [DEBUG] Dropped offset (noadvance): cluster=NJ topic=servingStatusEvent1 partition=48 group=galtest_004 timestamp=1467899190926 offset=1228 tsdiff=0 lag=262
2016-07-10 20:46:55 [DEBUG] Dropped offset (noadvance): cluster=NJ topic=servingStatusEvent1 partition=44 group=galtest_004 timestamp=1467899190936 offset=1236 tsdiff=0 lag=261
2016-07-10 20:46:55 [DEBUG] Dropped offset (noadvance): cluster=NJ topic=servingStatusEvent1 partition=59 group=galtest_004 timestamp=1467899190934 offset=1234 tsdiff=0 lag=261
2016-07-10 20:46:55 [DEBUG] Dropped offset (noadvance): cluster=NJ topic=servingStatusEvent1 partition=47 group=galtest_004 timestamp=1467899190916 offset=1227 tsdiff=0 lag=262
2016-07-10 20:46:55 [DEBUG] Dropped offset (noadvance): cluster=NJ topic=servingStatusEvent1 partition=45 group=galtest_004 timestamp=1467899190941 offset=1252 tsdiff=0 lag=257
2016-07-10 20:46:55 [DEBUG] Dropped offset (noadvance): cluster=NJ topic=servingStatusEvent1 partition=51 group=galtest_004 timestamp=1467899190917 offset=1234 tsdiff=0 lag=263

**Comment by imneo1** [comment] 2016-07-10 20:50
I think t works ok now. it just takes time

{
error: false,
message: "consumer group status returned",
status: {
cluster: "NJ",
group: "group1",
status: "OK",
complete: false,
partitions: [ ],
partition_count: 2000,
maxlag: null,
totallag: 0
},
request: {
url: "/v2/kafka/NJ/consumer/group1/status",
host: "burrow.our-domain.com",
cluster: "NJ",
group: "group1",
topic: ""
}
}

**Comment by imneo1** [comment] 2016-07-11 12:38
I stopped burrow, disabled the debug logging and let it run over night
i noticed it did not reach the "complete" state
i re-enabled logs and now i see it hangs on:

"Cannot get ZK notifier lock: zk: could not connect to a server"

I went to the burrow zookeeper and rmr burrow

started it again, and still get this ZK error...

if i don't use more than one burrow server, can i not use zookeeper for burrow (won't have this locking issue)

**Closed** 2016-07-13 17:51 UTC
