### ISSUE TITLE
gpm install error: cannot find package "github.com/klauspost/crc32"

### ISSUE THREAD

**Issue by shangd** [linkedin/Burrow#222] opened 2017-05-19 06:09 UTC
>> Getting package github.com/Shopify/sarama
>> Getting package github.com/pborman/uuid
>> Getting package gopkg.in/gcfg.v1
>> Getting package github.com/cihub/seelog
>> Getting package github.com/samuel/go-zookeeper/zk
>> Setting github.com/samuel/go-zookeeper/zk to version ad552be7b78b762b4a8040ffc5518bdaf5b7225d
>> Setting github.com/cihub/seelog to version 92dc4b8b540607b8187cc2f95cac200211dcd745
>> Setting gopkg.in/gcfg.v1 to version 0ef1a8547f99b94fac9af5377dd72febba18f37c
>> Setting github.com/pborman/uuid to version ca53cad383cad2479bbba7f7a1a05797ec1386e4
>> Setting github.com/Shopify/sarama to version 4ba9bba6adb6697bcec3841e1ecdfecf5227c3b9
>> Building package github.com/samuel/go-zookeeper/zk
>> Building package github.com/Shopify/sarama
../../Shopify/sarama/crc32_field.go:6:2: cannot find package "github.com/klauspost/crc32" in any of:
        /usr/local/go/src/github.com/klauspost/crc32 (from $GOROOT)
        /go/src/github.com/klauspost/crc32 (from $GOPATH)

Using go 1.8 and gpm 1.4.0, building from master branch

Strangely the build was last working in 27/April, and I don't see any new commit in master since then. Since sarama is commit-hash locked, I can't figure out what has changed.

**Comment by rabun788** [comment] 2017-05-24 16:05
+1

**Comment by krolen** [comment] 2017-05-26 17:52
Another option would be adding:

github.com/klauspost/crc32          1bab8b35b6bb565f92cbc97939610af9369f942a

to Godeps file
It is a bit better since you specifying exact version you want to have.

I agree that it is strange that it is stopped working. In general whole project look a bit abounded to me: related ui project fails building as well.

**Comment by freakynit** [comment] 2017-06-01 07:43
Adding to godeps looks good. Had faced the same issue

**Comment by toddpalino** [comment] 2017-06-25 14:51
Thanks for finding the Godeps issue. If you submit a PR we can resolve this. I agree that it's odd that it stopped working with no changes in deps.

@krolen, to address some of your concerns, the project is not abandoned - I just don't get a lot of time to work on it and most of the changes I make are driven by what we need to use Burrow internally. Burrow works just fine with offsets committed to Kafka - in fact that's how it was designed to work, and Zookeeper was added afterwards.

**Comment by toddpalino** [comment] 2017-09-28 21:19
Resolved by #234

**Closed by toddpalino** 2017-09-28 21:19 UTC
