### ISSUE TITLE
Burrow re-creates topics

### ISSUE THREAD

**Issue by Antwnis** [linkedin/Burrow#82] opened 2016-06-23 18:05 UTC
After deleting & re-installing Kafka, burrow re-creates the topics that it was checking

**Comment by toddpalino** [comment] 2016-06-23 18:34
Yes, sadly, it very much does. Unfortunately, this is not really a burrow problem, it's a problem with Kafka itself when you have auto topic creation enabled (as we do). The metadata request that Burrow performs for each topic has the side effect of creating the topic if it doesn't exist.

There's not a lot that can be done about this from an automated point of view. You could just shut Burrow down and restart it when you wipe out a cluster like that, which is what I normally do. Another option is to provide an API endpoint to delete a cluster, which you could ping between taking the cluster down and bringing it back up to wipe out all information about topics and groups in the cluster.

**Comment by Antwnis** [comment] 2016-06-23 18:40
Would it be painful to do an extra round-trip to zookeeper to fetch available topics and then only request metadata for the topics that actually exist ? Not sure around the frequency of polling..

**Comment by toddpalino** [comment] 2016-07-07 18:08
Burrow does not use Zookeeper for enumerating topics right now. The only use for Zookeeper is enumerating the `/consumers` tree for discovering consumer groups and offsets for consumers that commit to Zookeeper. Topic enumeration is done through metadata requests to the brokers.

One possibility would be to add a metadata expiration, such that the topic information from the Brokers is flushed entirely after some interval of not being refreshed. This would leave the consumer information in Burrow alerting, but at least it wouldn't damage the Kafka cluster.

**Comment by toddpalino** [comment] 2017-09-28 23:25
I'm going to address this problem in the 1.0 rewrite. The issue is that Burrow (and Sarama underneath) needs to use a null TopicMetadata request to enumerate the topics in the cluster, not a request with every topic listed. If Sarama doesn't have this capability exposed, I'll look at making an upstream change for that.

**Comment by toddpalino** [comment] 2017-12-01 15:58
Resolved by 1.0 rewrite

**Closed by toddpalino** 2017-12-01 15:58 UTC
Labels: bug
