### ISSUE TITLE
Lag always 0 in http notifier

### ISSUE THREAD

**Issue by mcorbin** [linkedin/Burrow#126] opened 2016-08-29 15:51 UTC
I have a topic consumed by only one consumer. I configured Burrow to be notified over http.
When i stop the consumer, the consumer lag is increasing (i can see it in kafka manager). 

But when i check the lag field on my http server, it is always zero : 
{"topic": "mytopicname", "status": "STOP", "partition": 0, "end": {"timestamp": 1472484537250, "lag": 0, "offset": 74999}

Here is my configuration : 

```
[zookeeper]
hostname=zookeeper_hostname

[kafka "test"]
broker=kafka_hostname
zookeeper=zookeeper_hostname
zookeeper-port=2181
zookeeper-path=/

[httpserver]
server=on
port=9091

[httpnotifier]
url=http_url
interval=60
template-post=/etc/burrow/template_post.tmpl
timeout=5
keepalive=30
template-delete=/etc/burrow/template_del.tmpl

[emailnotifier "my@email.com"]
group=test,group1
group=test,group2
interval=10
```

Is something wrong in my configuration ?

**Comment by toddpalino** [comment] 2016-08-30 15:21
This is a known issue with the way Burrow currently tracks lag for consumers. Lag is only associated with specific offset commits, and is calculated at the time of the offset commit. This means that when a consumer stops, Burrow will alert for stopped partitions but has no way to update the lag numbers.

Closing this as a duplicate of #127, which will track a solution to this problem.

**Closed by toddpalino** 2016-08-30 15:21 UTC
